### PR TITLE
rename param container administration_languages

### PR DESCRIPTION
**Pull request by itkg-ngilain**
https://github.com/open-orchestra/open-orchestra-base-bundle/pull/27
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/859

### CODE REVIEW

**Comment by nicolasThal** [comment]
We could wait until the next tag for this modification

**Comment by itkg-ngilain** [comment]
Ok, I'll check it tomorrow

**Comment by itkg-ngilain** [comment]
@nicolasThal : is it ok for you now ?

**Comment by nicolasThal** [comment]
yes :+1:

**Pull request merged**
